### PR TITLE
Set repositories to use HTTPS and enable GPG check

### PR DESCRIPTION
**Pull request by kustodian**
Because security is important, I set all repositories to use HTTPS and enabled GPG checks.

### CODE REVIEW

**Comment by gooodmorningopenstack** [comment]
At least for Debian, the `apt-transport-https` package ends up to be a dependency for that to run. We should include that in the tasks.

We should also rework the `tasks/` files list to be larger than `pkg-something`.

**Comment by alessfg** [comment]
I am all for making the packages more secure @kustodian 😄 Could we maybe fetch the signing key from a keyserver just like the NGINX Dockerfile does (https://github.com/nginxinc/docker-nginx/blob/master/mainline/stretch/Dockerfile#L12)? The apt-key module seems to implement this functionatility.

Good catch @gooodmorningopenstack. I am in the process of setting up an automated testing environment but for now each PR has to be manually tested in all distros listed in https://github.com/nginxinc/ansible-role-nginx-oss#requirements

**Comment by kustodian** [comment]
@alessfg what is the problem with fetching the key as it is done now?

**Comment by alessfg** [comment]
There is no problem per se. It's just more secure to fetch a key from a keyserver than directly from a URL.

**Comment by gooodmorningopenstack** [comment]
:+1: for Keyservers, GPG check and HTTPS. We really want to use sane default variables for these Keyservers URL and manage the necessary dependencies per OS distribution, otherwise it's not so serious in my opinion

**Comment by alessfg** [comment]
I have released a new [NGINX Ansible role](https://github.com/nginxinc/ansible-role-nginx) that uses `HTTPS` and `GPG` checks wherever possible.

**Pull request closed without merging**
