### PR TITLE
feat(testingStrategy) ensure that role_path is always set adequatly

### PR DESCRIPTION
**Pull request by gooodmorningopenstack**
Hello,

as https://github.com/nginxinc/ansible-role-nginx-oss/issues/2 mentions, the role_path isn't set for local run, it's only working within Travis CI (because it's included at runtime).

Here is a fix that should let both run successfully with some tweak in `ansible.cfg`

### CODE REVIEW

**Comment by alessfg** [comment]
I you check my comment on #2 you'll see that I am not entirely sure that the error is due to the role_path not being properly set. Anything within the `tests` subfolder is only included there for Travis CI and should not be used for deploying the role. I've updated the README to reflect this. Let's wait to see what/if @bolek2000 replies to my comment on #2 and reevaluate.

**Comment by gooodmorningopenstack** [comment]
I was fixing the testing strategy, which must be portable along Travis or *any* environment (localhost, another CI, whatever).

There is nothing related to deploying through `tests` or the `include` change that Ansible 2.4 implies.

**Comment by alessfg** [comment]
I see. In that case it does make more sense, my testing strategy did hinge on Travis CI but you make a valid point. While it does not seem to the standard practice in most Ansible Roles I've researched so far (they tend to stick to Travis CI) I agree that implementing a testing strategy that works across multiple environments is a huge bonus.

**Comment by alessfg** [comment]
Still unsure on how to best proceed on this matter, but since there is a new [NGINX Ansible role](https://github.com/nginxinc/ansible-role-nginx) it makes no sense to continue the discussion here.

**Pull request closed without merging**
